language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
- '0.6'
env:
  matrix:
  - secure: lbYNrGvzoL8zcRteqZni8nUNwUmfyfTHqsLU0i/2a3U7fqwd/HXgAfjZhb+yx08uDj/r5oIhdDRfkztU4N9GzpZ+eZHoDaBDiy3yD4tm3o0CsZ+YrxIcaK5Zvmf1AZUO254fM64fM8jL66LJZt1OaI2+XvylifJgyh/D366hPkQ=
  - secure: kshZWyPhYp4vieHXHmiO5SBVU0EGT26YmCd3J0mYBG74yHSCtVIpUQtkxRWyv2Sxp1DTbfRSz7+257XdiGLCo5wd1pr6VXVfFe1MH8WZA5HahEUaAvHz+d1WB2CAfUZr7fFjCs747LhjnmxEg+l9kU12ehdNiskdLykgSAE0Fqw=
