language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
- '0.6'
env:
  global:
  - secure: EmNPHtoDLqGiCf3rZShhTf0R6CWrOPFkHUx9fwpUEBAbZNhUVktNzU6I646uozNg7ejddij+98ak/pEMITo3Iv4sS1TGqqVAnHZ18MZ+q+skgst/+fBl9DYzIW8GspWQLNNQKMYzTobMCDwYy/T32Y/9TlmO64ELsw3GeMoIc04=
  - secure: bZUEFI0rhNRQ8NLvt68hx4biGGP3u/K8UJPVNWuIZxkZEBvF3NBaOT9D8Ho0z0HTVJGZ9xYH6S9qcuJgsCnbMrGEWBA30wyN6BeZ0s21oxoKp1o1mcuUelDsXRmt5yV2uDzTHQTaLKB8frbS0yLKsH+PMlcJ7bKCMiV8Q6hL0qQ=
